nodeLinker: node-modules
npmPublishAccess: public
npmScopes:
  usebridge:
    npmRegistryServer: "https://registry.npmjs.org"
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN:-}"

# Disable Git ancestry checks for version commands
changesetBaseRefs: []

# Kill all git side effects when bumping versions
versionCommitHooks: false
versionGitMessage: ""
versionTagPrefix: ""
versionSignGitCommit: false
