name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"

      - name: Enable Corepack & pin Yarn
        run: |
          corepack enable
          corepack prepare yarn@$(node -p "require('./package.json').packageManager.split('@')[1]") --activate
          yarn --version

      - name: Install deps
        run: yarn install --immutable

      - name: Build (all)
        run: yarn build

      - name: Create Release PR or Publish
        uses: changesets/action@v1
        with:
          publish: "yarn release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
