name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@usebridge"

      - name: Install deps
        run: yarn install --immutable

      - name: Set version on packages
        run: |
          VERSION=${{ github.event.release.tag_name }}
          # Remove 'v' prefix if present
          VERSION=${VERSION#v}

          # Update core package version
          cd packages/core
          npm version $VERSION --no-git-tag-version

          # Update react package version  
          cd ../react
          npm version $VERSION --no-git-tag-version

      - name: Build and Publish packages
        run: yarn turbo run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
